cc_library(
    name = "minLib",
    srcs = [
        "minpriority.cpp",
    ],
    hdrs = [
        "minpriority.h"
    ],
)
cc_binary(
    name = "main",
    srcs = [
            "main.cpp"
    ],
    deps = [
        ":minLib",
    ],
)
